//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanalMuze.MetarialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Material", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Material : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageFilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddedDateField;
        
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletionDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ImageFilePath {
            get {
                return this.ImageFilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageFilePathField, value) != true)) {
                    this.ImageFilePathField = value;
                    this.RaisePropertyChanged("ImageFilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WhoAdded {
            get {
                return this.WhoAddedField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoAddedField, value) != true)) {
                    this.WhoAddedField = value;
                    this.RaisePropertyChanged("WhoAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AddedDate {
            get {
                return this.AddedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AddedDateField, value) != true)) {
                    this.AddedDateField = value;
                    this.RaisePropertyChanged("AddedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DeletionDate {
            get {
                return this.DeletionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletionDateField, value) != true)) {
                    this.DeletionDateField = value;
                    this.RaisePropertyChanged("DeletionDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MetarialService.GetMeterialDetailsSoap")]
    public interface GetMeterialDetailsSoap {
        
        // CODEGEN: Generating message contract since element name GetMaterialsDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaterialsDetails", ReplyAction="*")]
        SanalMuze.MetarialService.GetMaterialsDetailsResponse GetMaterialsDetails(SanalMuze.MetarialService.GetMaterialsDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaterialsDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<SanalMuze.MetarialService.GetMaterialsDetailsResponse> GetMaterialsDetailsAsync(SanalMuze.MetarialService.GetMaterialsDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaterialsDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaterialsDetails", Namespace="http://tempuri.org/", Order=0)]
        public SanalMuze.MetarialService.GetMaterialsDetailsRequestBody Body;
        
        public GetMaterialsDetailsRequest() {
        }
        
        public GetMaterialsDetailsRequest(SanalMuze.MetarialService.GetMaterialsDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMaterialsDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int inID;
        
        public GetMaterialsDetailsRequestBody() {
        }
        
        public GetMaterialsDetailsRequestBody(int inID) {
            this.inID = inID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaterialsDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaterialsDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SanalMuze.MetarialService.GetMaterialsDetailsResponseBody Body;
        
        public GetMaterialsDetailsResponse() {
        }
        
        public GetMaterialsDetailsResponse(SanalMuze.MetarialService.GetMaterialsDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMaterialsDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SanalMuze.MetarialService.Material[] GetMaterialsDetailsResult;
        
        public GetMaterialsDetailsResponseBody() {
        }
        
        public GetMaterialsDetailsResponseBody(SanalMuze.MetarialService.Material[] GetMaterialsDetailsResult) {
            this.GetMaterialsDetailsResult = GetMaterialsDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetMeterialDetailsSoapChannel : SanalMuze.MetarialService.GetMeterialDetailsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMeterialDetailsSoapClient : System.ServiceModel.ClientBase<SanalMuze.MetarialService.GetMeterialDetailsSoap>, SanalMuze.MetarialService.GetMeterialDetailsSoap {
        
        public GetMeterialDetailsSoapClient() {
        }
        
        public GetMeterialDetailsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetMeterialDetailsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMeterialDetailsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetMeterialDetailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SanalMuze.MetarialService.GetMaterialsDetailsResponse SanalMuze.MetarialService.GetMeterialDetailsSoap.GetMaterialsDetails(SanalMuze.MetarialService.GetMaterialsDetailsRequest request) {
            return base.Channel.GetMaterialsDetails(request);
        }
        
        public SanalMuze.MetarialService.Material[] GetMaterialsDetails(int inID) {
            SanalMuze.MetarialService.GetMaterialsDetailsRequest inValue = new SanalMuze.MetarialService.GetMaterialsDetailsRequest();
            inValue.Body = new SanalMuze.MetarialService.GetMaterialsDetailsRequestBody();
            inValue.Body.inID = inID;
            SanalMuze.MetarialService.GetMaterialsDetailsResponse retVal = ((SanalMuze.MetarialService.GetMeterialDetailsSoap)(this)).GetMaterialsDetails(inValue);
            return retVal.Body.GetMaterialsDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SanalMuze.MetarialService.GetMaterialsDetailsResponse> SanalMuze.MetarialService.GetMeterialDetailsSoap.GetMaterialsDetailsAsync(SanalMuze.MetarialService.GetMaterialsDetailsRequest request) {
            return base.Channel.GetMaterialsDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SanalMuze.MetarialService.GetMaterialsDetailsResponse> GetMaterialsDetailsAsync(int inID) {
            SanalMuze.MetarialService.GetMaterialsDetailsRequest inValue = new SanalMuze.MetarialService.GetMaterialsDetailsRequest();
            inValue.Body = new SanalMuze.MetarialService.GetMaterialsDetailsRequestBody();
            inValue.Body.inID = inID;
            return ((SanalMuze.MetarialService.GetMeterialDetailsSoap)(this)).GetMaterialsDetailsAsync(inValue);
        }
    }
}
